create table public.tbl_admin (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  admin_name text null,
  admin_email text null,
  admin_password text null,
  auth_id uuid null,
  constraint tbl_admin_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tbl_complaint (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  complaint_title text null,
  complaint_content text null,
  complaint_status text null,
  complaint_reply text null,
  complaint_user_id uuid null,
  constraint tbl_complaint_pkey primary key (id),
  constraint tbl_complaint_complaint_user_id1_fkey foreign KEY (complaint_user_id) references tbl_user (id)
) TABLESPACE pg_default;

create table public.tbl_crime (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  crime_lan text null,
  crime_log text null,
  crime_details text null,
  crime_status text null,
  crime_type_id bigint null,
  crime_subject text null,
  crime_user_id uuid null,
  constraint tbl_crime_pkey primary key (id),
  constraint tbl_crime_crime_user_id1_fkey foreign KEY (crime_user_id) references tbl_user (id),
  constraint tbl_crime_type_id_fkey foreign KEY (crime_type_id) references tbl_type (id)
) TABLESPACE pg_default;

create table public.tbl_feedback (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  feedback_content text null,
  feedback_user_id uuid null,
  constraint tbl_feedback_pkey primary key (id),
  constraint tbl_feedback_feedback_user_id1_fkey foreign KEY (feedback_user_id) references tbl_user (id)
) TABLESPACE pg_default;

create table public.tbl_notification (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  notification_crime_id bigint null,
  notification_user_id uuid null default gen_random_uuid (),
  constraint tbl_notification_pkey primary key (id),
  constraint tbl_notification_notification_crime_id_fkey foreign KEY (notification_crime_id) references tbl_crime (id),
  constraint tbl_notification_notification_user_id_fkey foreign KEY (notification_user_id) references tbl_user (id)
) TABLESPACE pg_default;

create table public.tbl_officials (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  officials_name text null,
  officials_email text null,
  officials_password text null,
  officials_address text null,
  officials_photo text null,
  officials_proof text null,
  officials_status text null,
  officials_phone text null,
  auth_id uuid null default gen_random_uuid (),
  constraint tbl_officials1_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tbl_type (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  type_name text null,
  constraint tbl_type_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tbl_user (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  user_name text null,
  user_email text null,
  user_password text null,
  user_address text null,
  user_proof text null,
  user_photo text null,
  user_status text null,
  user_lan text null,
  user_log text null,
  auth_id uuid null default gen_random_uuid (),
  user_phone text null,
  constraint tbl_user_pkey primary key (id),
  constraint tbl_user_user_phone_check check ((length(user_phone) = 10))
) TABLESPACE pg_default;